Add user administration pages
SpongePowered/Ore pull request #377
Opened 2018-01-19 02:52 UTC by simon816

Closes #354

WIP: Currently just a page mock-up, backend still todo.

Current mock-up:
![image](https://user-images.githubusercontent.com/1497508/35132532-a29485d0-fcc3-11e7-970c-a54bf0ede22c.png)

2018-01-20 21:18 UTC, phase requested changes

2018-01-20 21:18 UTC, phase commented on app/views/users/view.scala.html
> +                            @if(users.current.isDefined && users.current.get.can(ViewAdmin).in(user)) {
`users.current.get can ViewAdmin in user` would be more consistent with the rest of the code

2018-01-20 21:18 UTC, phase commented on app/views/users/admin/userAdmin.scala.html
> +@bootstrap.layout((if(isOrg) "Organization" else "User") + " Admin - " + user.username) {
I don't think this is giving me the information I want. Seeing `User Admin - simon` confuses me. Is `simon` an Admin? What does this page do? `Edit User - simon` would be clearer.

2018-01-20 21:18 UTC, phase commented on app/ore/permission/Permission.scala
> +case object ViewAdmin           extends Permission { val trust = Absolute }
I'd give this to `Lifted` since they can already edit settings.

2018-01-20 21:18 UTC, phase commented on app/views/users/admin/userAdmin.scala.html
> +                        <a href="@config.security.getString("api.url").get/admin/accounts/user/@user.id/change/">SpongeAuth Admin</a>
`SpongeAuth Profile` would be consistent with `Forum Profile` below.

2018-01-20 21:20 UTC, phase commented
![t](https://cdn.discordapp.com/attachments/196511141042585600/404384418061352980/unknown.png)

There seem to be some lines missing in some of the tables.

2018-01-21 00:49 UTC, simon816 commented
I have implemented the backend code now. Not very majestic but gets the job done.

2018-01-28 18:38 UTC, progwml6 commented
This PR has merge conflicts that must be resolved

2018-01-28 21:50 UTC, simon816 commented
rebased

2018-01-29 05:26 UTC, phase commented
Did you fix the lines I pointed out?

2018-01-29 20:23 UTC, simon816 commented
@phase Yes

2018-01-29 21:02 UTC, merged