Add staff activity overview
SpongePowered/Ore pull request #380
Opened 2018-01-19 22:41 UTC by Ewoutvans

Real simple:

Click tag on profile page of the user
![schermafbeelding 2018-01-19 om 23 41 10](https://user-images.githubusercontent.com/3961526/35175073-456a0cae-fd72-11e7-910e-3f381510cf95.png)

See what he did ordered by date:
![schermafbeelding 2018-01-19 om 23 40 55](https://user-images.githubusercontent.com/3961526/35175085-51f43dd2-fd72-11e7-84b7-08f002d6a24a.png)

2018-01-20 00:19 UTC, phase requested changes

2018-01-20 00:19 UTC, phase commented on app/views/users/admin/activity.scala.html
> +                                    <td>Review approved:</td>
Have this link to the review

2018-01-20 00:19 UTC, phase commented on app/views/users/admin/activity.scala.html
> +                                    <td>Flag resolved:</td>
Have this link to whatever project got flagged (or if there's a "flag" page link to that)

2018-01-20 00:19 UTC, phase commented on app/views/users/view.scala.html
> +                            @if(users.current.isDefined && users.current.get.can(ViewActivity).in(user)) {
`users.current.get can ViewActivity in user ` would be more consistent with the rest of the code

2018-01-20 00:19 UTC, phase commented on app/controllers/Application.scala
> +  def sortMethod(o1: Object, o2: Object): Boolean = {
Can we get a better name for this? `compareObjects` or something.

2018-01-20 21:23 UTC, phase commented
Why is the link on the tag? I think a calendar icon next to the existing buttons would look more consistent.

The activity page is also very bland. Maybe a white background underneath the text?

2018-01-20 21:39 UTC, Ewoutvans commented
@phase I changed it to a calendar & added the table to a panel so its more like the rest of the site
I've updated the screenshots

2018-01-27 09:37 UTC, kashike approved these changes

2018-01-27 19:49 UTC, phase approved these changes

2018-01-28 16:37 UTC, merged