Removed rounded corners and some other minor fixes
SpongePowered/Ore pull request #404
Opened 2018-01-31 17:32 UTC by felixoi

![Screenshot from Gyazo](https://i.gyazo.com/291a7322c913cb0fe46f2ca7f4848a1b.png)

Hope this makes some guys happy :100:

2018-01-31 17:53 UTC, phase requested changes
Looks good so far.

2018-01-31 17:53 UTC, phase commented on app/assets/stylesheets/main.scss
> +  border: 1px solid #ddd;
I'd prefer these be in variables.

2018-02-01 00:03 UTC, progwml6 commented on app/assets/stylesheets/main.scss
> +  border: 1px solid #ddd;
all colors should be in variables

2018-02-04 06:30 UTC, Grinch commented
Hallelujah!

2018-02-07 20:09 UTC, Ewoutvans approved these changes

2018-02-07 20:11 UTC, merged