Add Visibility states
SpongePowered/Ore pull request #429
Opened 2018-02-11 17:32 UTC by Ewoutvans

![schermafbeelding 2018-02-11 om 18 21 19](https://user-images.githubusercontent.com/3961526/36076121-888021fc-0f58-11e8-9932-1298ebd85517.png)
![schermafbeelding 2018-02-11 om 18 27 22](https://user-images.githubusercontent.com/3961526/36076243-d678aee6-0f59-11e8-9157-5ab66bcc644e.png)
![schermafbeelding 2018-02-11 om 18 21 49](https://user-images.githubusercontent.com/3961526/36076123-8bc8dbec-0f58-11e8-81eb-5e8dc26dfe85.png)

This introduces the states from #413 
Deleting & NeedsChanges will be in a separate PR

2018-02-11 21:06 UTC, phase requested changes
This is looking awesome!

2018-02-11 21:06 UTC, phase commented on conf/evolutions/default/86.sql
> +ALTER TaBLE projects ADD COLUMN is_visible BOOLEAN default TRUE;
typo in `TaBLE`

2018-02-11 21:06 UTC, phase commented on app/ore/project/ProjectTask.scala
> +        Logger.info(s"Project ${project.ownerName}/${project.slug} is still in Draft changing to Public")
`Change $owner/$slug visibility from Draft to Public` would be a little clearer.

2018-02-11 21:06 UTC, phase commented on app/controllers/Application.scala
> +            +&& ((ModelFilter[Project](_.visibility === VisibilityTypes.NeedsChanges) +|| ModelFilter[Project](_.visibility === VisibilityTypes.Draft))))
Doesn't this leave out projects that the user owns that `NeedsApproval`? I think checking for `ModelFilter[Project](_.visibility =!= VisibilityTypes.SoftDelete)` would be cleaner.

2018-02-11 21:39 UTC, dualspiral commented
I'd like to suggest a change to the text you have in the red box you have on a draft page. I assume it's user facing - it's written in the third person so looks odd on a message directed at the author. Most users won't see that message because the project is hidden! I'd suggest something like the following might be better (calculating the time remaining before publish):

"This project is hidden for the next xx hours to allow you to add your project's documentation, after which your project will be published automatically. Once you have completed added documentation, you can choose to publish your project early by clicking the "Publish" button."

I'm open to that being rephrased, but that message needs to be author targeted, not third-person targetted.

2018-02-11 21:42 UTC, dualspiral commented
...just realised, the draft page isn't going to be hidden, is it? I misread what was in the ore channels and whatnot.

Still, the message should be different for authors and users. If users see that, the first line of what you have is fine. Sorry for any confusion!

2018-02-11 22:00 UTC, Ewoutvans commented
no draft is hidden, we changed it after some discussions

2018-02-12 00:09 UTC, mbax commented
To avoid confusion, I'd like to see 'draft' renamed to 'new' or 'newproject'. That way, if we decide we want an actual drafting process we can do that later.

2018-02-15 17:41 UTC, felixoi approved these changes

2018-02-15 17:45 UTC, merged