Allow sending a changelog when using the deploy API endpoint
SpongePowered/Ore pull request #471
Opened 2018-03-03 12:20 UTC by Katrix-

Does as it says. Allows sending an optional changelog when using the deploy API endpoint.

2018-03-03 15:22 UTC, mbax commented on app/controllers/ApiController.scala
> +
Why the extra line?

2018-03-03 16:06 UTC, Katrix- commented on app/controllers/ApiController.scala
> +
Ah, I guess a newline sneaked in. Probably though something along the lines of separating updating the model to publishing the version. I can remove it if you want.

2018-03-03 22:18 UTC, phase requested changes

2018-03-03 22:18 UTC, phase commented on app/controllers/ApiController.scala
> +
go ahead and remove it and I'll merge

2018-03-04 18:20 UTC, progwml6 commented
Support for this needs to be added to the gradle plugin

2018-03-05 15:41 UTC, progwml6 commented
This will need to be added to the api docs as well

2018-03-05 19:02 UTC, progwml6 commented
this PR has conflicts, and MUST be verified by 2 developers to ensure that it has protections from the issue patched in 9afb3b748abbb9673c4342d3d5211cfc3487d396

2018-03-05 19:48 UTC, phase commented
This is safe. All key stuff was fixed already.

2018-03-06 09:17 UTC, Katrix- commented
Rebased and resolved merge conflicts.

2018-03-12 19:58 UTC, phase approved these changes
I'm fine with merging this, no security issues anywhere.

2018-03-13 00:31 UTC, progwml6 commented
This still needs to be implemented in the gradle plugin @phase

2018-03-13 00:40 UTC, Katrix- commented
I have the update for the Gradle plugin lying around somewhere, just give me a day to test that it works.

2018-04-13 03:52 UTC, merged