Add post to forums toggle
SpongePowered/Ore pull request #472
Opened 2018-03-03 16:25 UTC by Katrix-

Adds a setting to toggle if Ore actions (currently only creating releases) should automatically also create a new forums post.

Also did some housekeeping to ensure that a post is actually created (unless the setting says otherwise) on the forums no matter how the version was created (previously, if a version were created through the API, a post would not be created).

Bit unsure if I covered everything here as this is probably my biggest pull request so far. As I can't test the forums integration, I haven't tested that the toggle work, but I see no reason for it not to.

Closes #322

2018-03-03 17:24 UTC, Ewoutvans requested changes

2018-03-03 17:24 UTC, Ewoutvans commented on app/views/projects/settings.scala.html
> +                                postReleasesToForum = settings.postReleasesToForum
this doesn't compile I believe it has to be `settings.postToForums`

2018-03-03 17:24 UTC, Ewoutvans commented on conf/evolutions/default/91.sql
> +ALTER TABLE project_settings DROP COLUMN post_to_forums;
Add a newline

2018-03-03 17:24 UTC, Ewoutvans commented on app/views/projects/utils/inputSettings.scala.html
> +                    class="form-control" id="forums" name="post-to-forums">
Due to the `form-control` the text is on a new line and it looks strange:
<img width="890" alt="schermafbeelding 2018-03-03 om 18 02 58" src="https://user-images.githubusercontent.com/3961526/36937013-3c960e86-1f0d-11e8-9c51-9fdfc14d1595.png">
I think its better like this
<img width="924" alt="schermafbeelding 2018-03-03 om 18 04 19" src="https://user-images.githubusercontent.com/3961526/36937017-4fbe66a2-1f0d-11e8-9993-08244bcc9f9d.png">

2018-03-03 17:55 UTC, felixoi commented
Does this still adds the first forum post on project creation?

2018-03-03 17:58 UTC, Ewoutvans commented
@felixoi as far as I tested yes.

2018-03-03 18:07 UTC, felixoi commented
Then I would suggest to rename `postToForums` to `forumSync` or similar. It's a much cleaner name for it.

2018-03-03 18:22 UTC, Katrix commented
Thanks for all the suggestions. Pushed some changes with fixes and new and better names.

2018-03-03 18:59 UTC, Ewoutvans commented
@Katrix- Looks great! 

May I suggest you could override the 'global setting' when you do an individual upload?
Like for instance I upload for API 5,7,8 and only want 1 message for the latter one on the forums.
Seems nice to have but isn't really specified in the issue

*Some where on this screen*
<img width="1180" alt="schermafbeelding 2018-03-03 om 19 53 46" src="https://user-images.githubusercontent.com/3961526/36938080-a4b2c27a-1f1c-11e8-984c-a78c3f6f3223.png">

2018-03-03 19:28 UTC, Ewoutvans approved these changes

2018-03-03 22:23 UTC, phase requested changes
I want the per-release override @Ewoutvans [described](https://github.com/SpongePowered/Ore/pull/472#issuecomment-370171263) before we merge. The rest looks good.

2018-03-05 18:37 UTC, Ewoutvans approved these changes

2018-03-05 18:53 UTC, phase approved these changes

2018-03-05 18:54 UTC, merged