Add Sync_SSO
SpongePowered/Ore pull request #509
Opened 2018-03-17 20:22 UTC by Ewoutvans

Add sync_sso

added 
- `/api/sync_sso`
- added `apikey` to config
- added `secret` to config

Closes #483

2018-03-17 20:55 UTC, Katrix- commented on app/controllers/ApiController.scala
> +          val decoded = URLDecoder.decode(new String(Base64.getMimeDecoder.decode(sso)), "UTF-8")
Play (through Akka) has nicer ways of dealing with query strings. Without looking too much into it, something like `Uri.Query(Base64.getMimeDecoder.decode(sso))` (charset is UTF-8 by default) is what you want to go with. Then call toMap on the result of that. From there, no more vars. Also as another tip, Scala provides a `toInt` method on strings to parse them as ints.

2018-03-17 21:34 UTC, progwml6 requested changes

2018-03-17 21:34 UTC, progwml6 commented on conf/application.conf.template
> +        secret = ${?SPONGE_AUTH_SSO_SYNC_SECRET}
we only need one SSO secret, remove this one

2018-03-17 21:34 UTC, progwml6 commented on conf/application.conf.template
> +        apikey = ${?SPONGE_AUTH_SSO_SYNC_APIKEY}
call this SPONGE_AUTH_SSO_API_KEY and move it up to the sso object

2018-03-19 04:33 UTC, Katrix- commented on app/controllers/ApiController.scala
> +          if (optUser.isEmpty) {
This statement does nothing in this position. Also not a fan of testing the content in this way. I'd say the best here would be a pattern match on optUser.

2018-03-22 06:47 UTC, Katrix requested changes

2018-03-22 06:47 UTC, Katrix- commented on app/controllers/ApiController.scala
> +            BadRequest(Json.obj("errors" -> Seq("User not found")))
This statement does not do anything in this position

2018-03-22 06:47 UTC, Katrix- commented on app/controllers/ApiController.scala
> +          email.map(user.email_=)
Prefer foreach for these instead of map

2018-03-22 06:47 UTC, Katrix- commented on app/controllers/ApiController.scala
> +          val external_id = query.get("external_id")
Bit unsure if we instead want to use normal camel case for these values

2018-03-22 06:47 UTC, Katrix- commented on app/controllers/ApiController.scala
> +        } else if (!CryptoUtils.hmac_sha256(confSecret, sso.getBytes("UTF-8")).equals(sig)) {
Use `==` instead of equals

2018-03-22 06:47 UTC, Katrix- commented on app/controllers/ApiController.scala
> +import java.net.URLDecoder
Check unused imports

2018-05-09 20:25 UTC, merged