Normalize db
SpongePowered/Ore pull request #674
Opened 2018-10-01 17:31 UTC by Katrix

Roles now exist in the db in their own table.
Tags no longer use an array for their versions.

2018-10-01 19:11 UTC, Ewoutvans requested changes

2018-10-01 19:11 UTC, Ewoutvans commented on app/db/impl/schema/tableSchema.scala
> +class DbRoleTable(tag: Tag) extends ModelTable[DbRole](tag, "roles") {
Why the sudden use of the 'Db' prefix?

2018-10-01 19:11 UTC, Ewoutvans commented on conf/evolutions/default/107.sql
> +VALUES (61, 'Ore_Admin', 'global', 5, 'Ore Admin', '#DC0000', TRUE, NULL),
Can we ditch the id's here?
I don't think it's wise to keep prolonging life to the old forumId system and if we migrate them it will only make it harder to remove it in the future.

@felixoi what do you think we should do.

2018-10-01 19:11 UTC, Ewoutvans commented on conf/evolutions/default/107.sql
> +CREATE INDEX role_name_idx ON roles (name);
I think this should be a unique index (I don't know if SpongeAuth forced uniqueness should probably be checked)

2018-10-01 20:00 UTC, Katrix commented on app/db/impl/schema/tableSchema.scala
> +class DbRoleTable(tag: Tag) extends ModelTable[DbRole](tag, "roles") {
Just to try to stay consistent with what appears to be the general rule for naming the tables (<ModelName>Table). Don't really think the table will see much use from Slick directly anyway.

2018-10-03 09:56 UTC, felixoi approved these changes

2018-10-08 12:54 UTC, Ewoutvans approved these changes

2018-10-08 13:10 UTC, felixoi requested changes
Tags are broken when using this PR.
It seems like you break it in the db since tags are still broken when switching back to master with the same database.

2018-10-08 17:14 UTC, phase reviewed
:clap: The version tags have been needing this for a while.

2018-10-27 14:43 UTC, felixoi commented on app/db/impl/schema/tableSchema.scala
> +class DbRoleTable(tag: Tag) extends ModelTable[DbRole](tag, "roles") {
Maybe rename it to `GlobalRoleTable`?

2018-10-27 21:04 UTC, Katrix commented on app/db/impl/schema/tableSchema.scala
> +class DbRoleTable(tag: Tag) extends ModelTable[DbRole](tag, "roles") {
1. that doesn't really describe what they are as they can be used in projects and orgs too. 2. I can't wait for one of use to ask the other what was the difference between `GlobalRolesTable` and `UserGlobalRolesTable`

2018-11-05 16:40 UTC, felixoi approved these changes

2018-11-05 16:41 UTC, merged