Only run task on visible projects and add some more sentry stuff
SpongePowered/Ore pull request #679
Opened 2018-10-05 19:35 UTC by Ewoutvans

2018-10-06 19:35 UTC, Katrix requested changes
Fix the imports. You're removing newlines which should be there

2018-10-08 13:15 UTC, felixoi requested changes

2018-10-08 13:15 UTC, felixoi commented on app/discourse/RecoveryTask.scala
> +    val topicFilter: ModelFilter[Project] = ModelFilter[Project](_.topicId === -1)
This will never be -1 anymore, it's null if no topic is created.

2018-10-08 17:01 UTC, felixoi approved these changes

2018-10-08 17:06 UTC, merged