Add the ability to update an organizations avatar
SpongePowered/Ore pull request #692
Opened 2018-10-20 09:39 UTC by Ewoutvans

Fixes #344

2018-10-22 11:54 UTC, Katrix requested changes

2018-10-22 11:54 UTC, Katrix commented on app/security/spauth/SpongeAuthApi.scala
> +case class ChangeAvatarToken(signed_data: String, target_username: String, request_user_id: Int) {}
Can we use camelCase here?

2018-10-22 11:54 UTC, Katrix commented on app/security/spauth/SpongeAuthApi.scala
> +          val obj = json.as[JsObject]
Are two as calls needed here?

2018-10-22 11:54 UTC, Katrix commented on app/controllers/Organizations.scala
> +      val res = token
You probably don't need this variable here

2018-10-22 11:54 UTC, Katrix commented on app/controllers/Organizations.scala
> +        .leftMap { err =>
Use _ instead of err here. Also, can you put it all on a single line?

2018-10-22 11:54 UTC, Katrix commented on app/controllers/Organizations.scala
> +          Future.successful(
semiFlatMap with successful? Just use map

2018-12-01 12:27 UTC, felixoi commented on app/security/spauth/SpongeAuthApi.scala
> +          val obj = json.as[JsObject]
I think so. Doesn't work without them

2018-12-01 14:06 UTC, Katrix commented on app/security/spauth/SpongeAuthApi.scala
> +          val obj = json.as[JsObject]
So `json. as[ChangeAvatarToken]` does not work?

2018-12-01 14:06 UTC, Katrix commented on app/security/spauth/SpongeAuthApi.scala
> +        .getOrElse(Left("error"))
Can you use toRight instead here?

2018-12-05 18:15 UTC, Katrix commented on app/security/spauth/SpongeAuthApi.scala
> +case class ChangeAvatarToken(signedData: String, targetUsername: String, requestUserId: Int) {}
Curly braces not needed here

2018-12-06 11:03 UTC, Katrix approved these changes

2018-12-07 17:27 UTC, merged