Add link icon on hover to links on markdown headers
SpongePowered/Ore pull request #759
Opened 2019-02-25 00:50 UTC by simon816

See image:
![image](https://user-images.githubusercontent.com/1497508/53308198-18df1100-3897-11e9-80d3-53194c648659.png)
Link icon is visible when hovering over the heading.

2019-02-27 21:54 UTC, felixoi requested changes

2019-02-27 21:54 UTC, felixoi commented on app/assets/stylesheets/_editor.scss
> +  h1:hover, h2:hover, h3:hover, {
Extra comma

2019-02-27 21:55 UTC, felixoi commented on app/assets/stylesheets/_editor.scss
> +    .headeranchor {
Please move it into single line selector like `h1:hover, h2:hover, h3:hover > .headeranchor`

2019-02-27 21:55 UTC, felixoi commented on app/assets/stylesheets/_editor.scss
> +    .headeranchor {
Same as above.

2019-02-27 21:56 UTC, felixoi commented
Looks good all in all, thanks for the PR! Just the little comma and nitpicking.

2019-02-28 21:21 UTC, simon816 commented
Fixed the comma. Using  `> .headeranchor` would be more ugly because you'd have to apply it to each comma-separated selector

2019-02-28 21:30 UTC, felixoi approved these changes

2019-02-28 21:32 UTC, merged